### PR TITLE
x: grc721 full refactor

### PR DESCRIPTION
**Pull request by leohhhn**
## Description

This is a refactor of the GRC721 package. The idea with this is that we want a fully "by-spec" implementation, and then we can build upon it and experiment.
 
The process of writing is done in Go, and later converted to Gno.

### CODE REVIEW

**Comment by linhpn99** [comment]
Can you assign me some issues to solve together ?

**Comment by n0izn0iz** [comment]
wdyt about using `[]byte` as tokenId type?
It would be a superset of eth's `uint256` while allowing tokens to have more self-describing and expressive keys

**Comment by leohhhn** [comment]
Hey @linhpn99 @n0izn0iz,

I've finished the implementation for this and added an example usage realm. If you want, you can take a look and tell me what you think.

**Comment by leohhhn** [comment]
Will move this code to the monorepo for visibility :)

**Comment by linhpn99** [comment]
> Will move this code to the monorepo for visibility :)



> Hey @linhpn99 @n0izn0iz,
> 
> I've finished the implementation for this and added an example usage realm. If you want, you can take a look and tell me what you think.


is it safe that you call panic() when handling the exception ?

**Comment by leohhhn** [comment]
@linhpn99 @n0izn0iz 

[Moved it](https://github.com/gnolang/gno/pull/2117) to the monorepo.

> Is it safe that you call panic() when handling the exception?

Will reply on the monorepo

**Pull request closed without merging**
